services:
  flowapp:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command:  ["rye", "run", "streamlit", "run", "flowapp/app.py"]

  flowqm:
    build:
      context: ./services/flowqm
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["python", "service.py"]