version: '3.8'

services:
  flowapp:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["/bin/bash", "-c", "source activate flowapp && streamlit run flowapp/app.py"]