apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowapp-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowapp-manager
  template:
    metadata:
      labels:
        app: flowapp-manager
    spec:
      containers:
      - name: flowapp-manager
        image: flowapp-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["streamlit", "run", "/app/app.py"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowapp-manager
spec:
  selector:
    app: flowapp-manager
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: NodePort