# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qm.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08qm.proto\x12\x02qm"\x1a\n\x04\x43\x65ll\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01"\x94\x01\n\x05\x41toms\x12\x10\n\x08\x65lements\x18\x01 \x03(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\x12\x0e\n\x06\x63harge\x18\x03 \x01(\x05\x12\x14\n\x0cmultiplicity\x18\x04 \x01(\x05\x12\x10\n\x03pbc\x18\x05 \x01(\x08H\x00\x88\x01\x01\x12\x1b\n\x04\x63\x65ll\x18\x06 \x01(\x0b\x32\x08.qm.CellH\x01\x88\x01\x01\x42\x06\n\x04_pbcB\x07\n\x05_cell"\xd0\x01\n\x11\x43\x61lculationParams\x12\x11\n\tcalc_type\x18\x01 \x01(\t\x12\x14\n\x0ctheory_level\x18\x02 \x01(\t\x12\x11\n\tbasis_set\x18\x03 \x01(\t\x12\x46\n\x11\x61\x64\x64itional_params\x18\x04 \x03(\x0b\x32+.qm.CalculationParams.AdditionalParamsEntry\x1a\x37\n\x15\x41\x64\x64itionalParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"L\n\tQMRequest\x12\x18\n\x05\x61toms\x18\x01 \x01(\x0b\x32\t.qm.Atoms\x12%\n\x06params\x18\x02 \x01(\x0b\x32\x15.qm.CalculationParams"w\n\nQMResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x18\n\x05\x61toms\x18\x03 \x01(\x0b\x32\t.qm.Atoms\x12\x0e\n\x06\x65nergy\x18\x04 \x01(\x01\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x05 \x01(\t2;\n\tQMService\x12.\n\x0b\x43\x61lculateQM\x12\r.qm.QMRequest\x1a\x0e.qm.QMResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "qm_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CELL.fields_by_name["values"]._options = None
    _CELL.fields_by_name["values"]._serialized_options = b"\020\001"
    _CALCULATIONPARAMS_ADDITIONALPARAMSENTRY._options = None
    _CALCULATIONPARAMS_ADDITIONALPARAMSENTRY._serialized_options = b"8\001"
    _globals["_CELL"]._serialized_start = 16
    _globals["_CELL"]._serialized_end = 42
    _globals["_ATOMS"]._serialized_start = 45
    _globals["_ATOMS"]._serialized_end = 193
    _globals["_CALCULATIONPARAMS"]._serialized_start = 196
    _globals["_CALCULATIONPARAMS"]._serialized_end = 404
    _globals["_CALCULATIONPARAMS_ADDITIONALPARAMSENTRY"]._serialized_start = 349
    _globals["_CALCULATIONPARAMS_ADDITIONALPARAMSENTRY"]._serialized_end = 404
    _globals["_QMREQUEST"]._serialized_start = 406
    _globals["_QMREQUEST"]._serialized_end = 482
    _globals["_QMRESPONSE"]._serialized_start = 484
    _globals["_QMRESPONSE"]._serialized_end = 603
    _globals["_QMSERVICE"]._serialized_start = 605
    _globals["_QMSERVICE"]._serialized_end = 664
# @@protoc_insertion_point(module_scope)
