# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import qm_pb2 as qm__pb2


class QMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
        ----
            channel: A grpc.Channel.
        """
        self.CalculateQM = channel.unary_unary(
            "/qm.QMService/CalculateQM",
            request_serializer=qm__pb2.QMRequest.SerializeToString,
            response_deserializer=qm__pb2.QMResponse.FromString,
        )


class QMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateQM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CalculateQM": grpc.unary_unary_rpc_method_handler(
            servicer.CalculateQM,
            request_deserializer=qm__pb2.QMRequest.FromString,
            response_serializer=qm__pb2.QMResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "qm.QMService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class QMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateQM(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qm.QMService/CalculateQM",
            qm__pb2.QMRequest.SerializeToString,
            qm__pb2.QMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
